# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: zip
      uses: montudor/action-zip@v0.1.0
      with:
          args: zip -qq -r ./bundle.zip ./
          working-directory: src/VideoReader/bin/Debug/net6.0/
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
          role-to-assume: arn:aws:iam::719727752067:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-2
    - name: ls
      run: ls -la
    - name: deploy
      run: aws lambda update-function-code --function-name arn:aws:lambda:us-east-2:719727752067:function:VideoReader --zip-file fileb://bundle.zip
    # - name: default deploy
    #   uses: appleboy/lambda-action@master
    #   with:
    #       function_name: VideoReader
    #       zip_file: bundle.zip
          
